model_params:
  name: 'ConditionalVAE'
  latent_dim: 128

data_params:
  data_path: "/content/drive/MyDrive/ECE_175B_Final_Project/Chip_Layouts/Chip_Dataset_4.0.pt"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 64
  num_workers: 2

exp_params:
  LR: 0.001
  weight_decay: 0.0
  kld_weight: 0.00020
  manual_seed: 42

soft_drc_params:
  use_soft_drc: False
  vanilla_weight: 5000.0  # <--- THE ANCHOR (Keep this static!)
  # The Physics Base Weights (Set to 1.0, let ALM do the scaling!)
  overlap_weight: 1.0
  area_weight: 1.0
  thermal_weight: 1.0
  sharpness_weight: 1.0
  cohesion_weight: 1.0
  
  target_area: 100.0  # (Keep this, it's a physical dimension, not a weight)

trainer_params:
  accelerator: "gpu" 
  devices: 1          
  # "/content/drive/MyDrive/ECE_175B_Final_Project/golden_vanilla_weights.ckpt"
  # "/content/checkpoints/ConditionalVAE/version_3/checkpoints/last.ckpt"
  resume_ckpt_path: "/content/checkpoints/ConditionalVAE/version_0/checkpoints/last.ckpt"
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  max_epochs: 25

logging_params:
  save_dir: "/content/checkpoints/"

  
