data_params:
  name: 'Real_Data'
  num_macros: [10, 15]
  widths_range: [10, 14]
  heights_range: [10, 14]
  power_range: [10, 15]
  grid_size: [64, 64]
  num_samples: 50000

finite_solver_params:
  conductivity: 148
  resolution: '1/64'
  tolerance: 1e-5
  iterations: 500

logging_params:
  save_path: "/content/drive/MyDrive/ECE_175B_Final_Project/Chip_Layouts"
  name: "Chip_Dataset"