data_params:
  name: 'Real_Data'
  num_macros: 10
  widths_range: [10, 15]
  heights_range: [10, 15]
  power_range: [10, 15]
  grid_size: [64, 64]
  num_samples: 10

finite_solver_params:
  conductivity: 148
  resolution: '1/64'
  iterations: 500

logging_params:
  save_path: "/content/drive/MyDrive/ECE_175B_Final_Project/Chip_Layouts"
  name: "Test_Run"