saving_params:
  # Swap this path when you want to evaluate different ablation models!
  img_path: "/content/drive/MyDrive/ECE_175B_Final_Project/Vanilla_CVAE/comparison.png"
  result_path: "/content/drive/MyDrive/ECE_175B_Final_Project/Vanilla_CVAE/eval_metrics.txt"
  save_visualizations: True

latent_optim:
  use_lso: False
  steps: 50
  lr: 0.05
